// eslint-disable-next-line @typescript-eslint/no-unused-vars
export const jsonElements = [
  {
    id: 0,
    name: "void",
    namev1: "Void",
    ascii: [" "],
    group: "Basic",
    description: "The void...",
    link: "./elements/void",
    active: false,
    tiles: "",
    absorption: 0,
    phase: 0,
    foregroundColor: "white",
    backgroundColor: "#2e006a",
    matrix: []
  },
  {
    id: 1,
    name: "laser",
    namev1: "Source",
    ascii: ["^", ">", "v", "<"],
    group: "Emitter",
    description: "A one-photon laser source",
    link: "./elements/laser",
    active: true,
    tiles: "",
    absorption: 0,
    phase: 0,
    foregroundColor: "white",
    backgroundColor: "black",
    matrix: []
  },
  {
    id: 2,
    name: "mirror",
    namev1: "ThinMirror",
    ascii: ["|", "/", "-", "\\", "|", "/", "-", "\\"],
    group: "Direction",
    description: "A simple reflecting mirror",
    link: "./elements/mirror",
    active: false,
    tiles: "",
    absorption: 0,
    phase: 0,
    foregroundColor: "white",
    backgroundColor: "black",
    matrix: []
  },
  {
    id: 3,
    name: "detector",
    namev1: "Detector",
    ascii: ["⇑", "⇒", "⇓", "⇐"],
    group: "Absorber",
    description: "A one-photon detector",
    link: "./elements/detector",
    active: false,
    tiles: "",
    absorption: 1,
    phase: 0,
    foregroundColor: "white",
    backgroundColor: "black",
    matrix: []
  },
  {
    id: 4,
    name: "rock",
    namev1: "Rock",
    ascii: ["#"],
    group: "Absorber",
    description: "An absorbing pet rock",
    link: "./elements/rock",
    active: false,
    tiles: "",
    absorption: 1,
    phase: 0,
    foregroundColor: "white",
    backgroundColor: "black",
    matrix: []
  },
  {
    id: 5,
    name: "mine",
    namev1: "Mine",
    ascii: ["!"],
    group: "Absorber",
    description: "An explosive mine (disarm Jean)",
    link: "./elements/mine",
    active: false,
    tiles: "",
    absorption: 1,
    phase: 0,
    foregroundColor: "white",
    backgroundColor: "black",
    matrix: []
  },
  {
    id: 6,
    name: "beamsplitter",
    namev1: "ThinSplitter",
    ascii: ["↑", "↗", "→", "↘", "↓", "↙", "←", "↖"],
    group: "Direction",
    description: "A beamsplitter",
    link: "./elements/beamsplitter",
    active: false,
    tiles: "",
    absorption: 0,
    phase: 0,
    foregroundColor: "white",
    backgroundColor: "black",
    matrix: []
  },
  {
    id: 7,
    name: "filter",
    namev1: "Absorber",
    ascii: ["-"],
    group: "Absorber",
    description: "A neutral density filter",
    link: "./elements/absorber",
    active: false,
    tiles: "",
    absorption: 0.5,
    phase: 0,
    foregroundColor: "white",
    backgroundColor: "black",
    matrix: []
  },
  {
    id: 8,
    name: "phaseinc",
    namev1: "VacuumJar",
    ascii: ["↝"],
    group: "Phase",
    description: "A glass slab that increases phase.",
    link: "./elements/phaseinc",
    active: false,
    tiles: "",
    absorption: 0,
    phase: 0.25,
    foregroundColor: "white",
    backgroundColor: "black",
    matrix: []
  },
  {
    id: 9,
    name: "phasedec",
    namev1: "Glass",
    ascii: ["↜"],
    group: "Phase",
    description: "Void that decreases phase.",
    link: "./elements/phasedec",
    active: false,
    tiles: "",
    absorption: 0,
    phase: -0.25,
    foregroundColor: "white",
    backgroundColor: "black",
    matrix: []
  }
];
